# -*- coding: utf-8 -*-
"""Spam Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wsGMOwZeEMb1NwQItIBxhqVf_45x2FwY

##
"""

# importing all libraries
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer # how many times word repeats
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB #multinomial gives count
data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/SMS-Spam-Detection/master/spam.csv", encoding= 'utf-8')
data.head()

data.shape

data = data [["class", "message"]]  #from this data, we are considering 2 features class and message

x = np.array(data["message"])
y = np.array(data["class"])
cv = CountVectorizer()
X = cv.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

clf = MultinomialNB()
clf.fit(X_train,y_train)

sample = input("Enter a message:")
data = cv.transform([sample]).toarray()
print(clf.predict(data))

